# Generated by Django 5.2.5 on 2025-08-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doce_gustu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefone (Login)'),
        ),
    ]
