# Generated by Django 5.2.5 on 2025-08-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doce_gustu_app', '0002_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
