# Generated by Django 5.2.5 on 2025-08-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doce_gustu_app', '0003_cliente_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
